### PR TITLE
add instanceid

### PR DESCRIPTION
**Pull request by bobxwang**
* instanceid
> add instanceid when register to eureka, default value is ip:appname:port
* heartbeat
> using time.tick to send heartbeat every 30 second
* readme
> add some info in readme

### CODE REVIEW

**Comment by bobxwang** [comment]
i also add actuator/info, actuator/health two endpoint when register to eureka, please check it, thanks. But I am a new guy in go language, maybe u can change it make it more go style

**Comment by bobxwang** [comment]
when register to eureka, the VipAddress and SecureVipAddress should set value strings.ToLower(app),otherwise the spring cloud gateway will not forword to router, it will say not found

**Comment by ArthurHlt** [comment]
Hi @bobxwang thanks for your PR, it looks like https://github.com/ArthurHlt/go-eureka-client/pull/9 was a solution to your problem, could you confirm that ?

In addition, in your PR, you were changing `SendHeartbeat` behaviour which can do a breaking changes.

I'm closing it for now, please re-open if you think it still lacks some functionnality

**Comment by dinuta** [comment]
Hi @ArthurHlt,

The Heartbeat should be sent regularly, from 30 to 30 seconds let's say, otherwise it gets evicted from the Eureka Server registry ?

How should I use this client, then ?

Can you advise? 

Right now my instance gets evicted from Eureka Registry.

func (c *Client) SendHeartbeat(appId, instanceId string) error  ->> sends it only once, right?

Thanks,
Catalin

**Pull request closed without merging**
