### PR TITLE
Set logging level

### LINKED ISSUE #4: No way to set logger level
Did not find a way to reduce logging level, other than forking the project and making source modifications. Would you accept pull requests to expose this? Or is there a solution?

### PR DESCRIPTION
**Pull request by loafoe**
Fixes #4

### CODE REVIEW

**Comment by ArthurHlt** [comment]
Thanks for the PR, i was more thinking about using a more common logger like [logrus](https://github.com/sirupsen/logrus). I could totally merge it but what's your thought about it ?

**Comment by loafoe** [comment]
Sounds good! Would this be done through a logging interface?

**Comment by ArthurHlt** [comment]
You can now use [logrus](https://github.com/sirupsen/logrus), i'm not sure about your question but you can set log level and format with logrus, let me know if you feel better with this interface

**Comment by loafoe** [comment]
@ArthurHlt logrus works for us yes! Thanks!

**Pull request closed without merging**
